config/routes.rb
KupiNam::Application.routes.draw do

  get "catalog_shops/index"
  get "parsings/index"

  root 'shops#index'
  resources :shops
  resources :parsings
  resources :catalog_shops

     resources :parsings do
       member do
         post 'get_catalogs'
         post 'get_goods'
       end
     end
    resources :save do
      member do
        post 'save_xls'
        post 'save_xlsx'
      end
    end

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :products
  has_many :catalog_shops
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
    @shop=Shop.all
  end

  def show
    @shop=Shop.find(params[:id])
  end

  def new
    @shop=Shop.new
  end

  def create
    @shop=Shop.new(shop_params)

    if @shop.save
      redirect_to @shop
    else
      render 'new'
    end
  end

  def edit
    @shop=Shop.find(params[:id])
  end

  def update
    @shop=Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to @shop
    else
      render 'edit'
    end
  end

  def destroy
    @shop=Shop.find(params[:id])
    @shop.destroy
    redirect_to shops_path
  end

  private
  def shop_params
    params.require(:shop).permit(:title,:url,:xpath,:host)
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def index
    @shop=Shop.all
  end

  def show
    @shop=Shop.find(params[:id])
  end

  def new
    @shop=Shop.new
  end

  def create
    @shop=Shop.new(shop_params)
    if @shop.save
      @parser=Parser.new
      redirect_to @shop
    else
      render 'new'
    end
  end

  def edit
    @shop=Shop.find(params[:id])
  end

  def update
    @shop=Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to @shop
    else
      render 'edit'
    end
  end

  def destroy
    @shop=Shop.find(params[:id])
    @shop.destroy
    redirect_to shops_path
  end

  private
  def shop_params
    params.require(:shop).permit(:title,:url,:xpath,:host)
  end
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/shops/_form.html.erb
<%= form_for @shop do |f| %>
    <% if @shop.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@shop.errors.count, "error") %> Исправте ошибки:</h2>
          <ul>
            <% @shop.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :url %><br>
      <%= f.text_field :url %>
    </p>
    <p>
      <%= f.label :xpath %><br>
      <%= f.text_field :xpath %>
    </p>
    <p>
      <%= f.label :host %><br>
      <%= f.text_field :host %>
    </p>
    <p>
      <%= label_tag "Excel файл" %><br>
      <button disabled="disabled">Выбрать</button>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/shops/edit.html.erb
<h1>Редактировать сайт</h1>

<%= render 'form' %>

<%= link_to 'Назад к списку сайтов', shops_path %>

app/views/shops/index.html.erb
<style type="text/css">
    .shop {
        border-bottom: 1px solid;
        margin: 0 30px;
    }

    .title_shop {
        float: left;
        margin-right: 20px;
        margin-left: 5px;
        font-size: 1.7em;

    }

    .title_shop a {
        color: #ffffff;
    }

    .button_to {
        float: right;
    }

    .list_cat {
        padding-left: 35px;
    }

    .none {
        display: none;
    }

    .catalog {
        font-size: 1.2em;
        float: left;
        font-weight: 700;
    }

    .catalog span {
        margin-right: 5px;
        position: relative;
        top: -2px;
    }

    .img_download {
        margin-left: 10px;
    }
.load{
    background-image: url("http://sampsonresume.com/labs/pIkfp.gif");
}

</style>
<script type="application/javascript">
    $(function () {
        $(".catalog").click(function (e) {
            e.preventDefault();
            var parent = $(this).parent().children("div");
            if (parent.children(".none").length > 0)
                parent.children("div").removeClass("none");
            else
                parent.children("div").addClass("none");
        });
        $('span.catalog_button>a').click(function (e) {
            e.preventDefault();
            var href = $(this).prop("href");
            var div = $(this).parent().children(".checkboxes")
            get_catalogs(href, div)
        });
        $('span.catalog_button>button').click(function () {
            var shop_id=$(this).parent().parent().attr("data-shop-id");
            var catalogs=[];
            $("input[data-shop-id='"+shop_id+"']").each(function(e){
                var ch=$(this).prop("checked");
                var ch2=$(this).attr("checked");
                if (ch)
                    catalogs.push($(this).val());
            });
            $(this).parent(".panel").children(".load").removeClass("none");
            setTimeout(parsing(catalogs,shop_id),100);
            $("div[@data-shop-id='"+shop_id+"']>span>div.info").html("<span>Парсинг...</span>");
            $("div[@data-shop-id='"+shop_id+"']>span>div.info").addClass('alert alert-info');
        });
        function get_catalogs(url, div_checkboxes) {
            $.ajax({
                url: url,
                method: 'POST',
                dataType: "json",
                timeout: 20000,
                success: function (data) {
                    var html = "";
                    for (var i = 0; i < data.length; i++) {
                        html += '<div class="list_cat"><input type="checkbox" name="checkbox[]" value="' + data[i].id + '" />' + data[i].title +
                                '<span class="label label-primary">' + data[i].count + '</span></div>';
                    }
                    if (html.length == 0)
                        html = "<span>Каталог пуст (Выполните обновление каталог)</span>"
                    $(div_checkboxes).html(html)

                },
                error: function (data) {
                    alert(data.value)
                }
            })
        }
        function parsing(catalogs, shop_id) {
            $.ajax({
                url: '/parsings/'+shop_id+'/get_goods',
                method: 'POST',
                dataType: "json",
                data:{catalogs:catalogs},
                timeout: 1000*60*60*4,
                success: function (data) {
                    var checkboxes='<div class="list_cat">';
                    for(var i=0;i<data.catalogs.length;i++){
                        checkboxes+='<input type="checkbox" data-shop-id="'+shop_id+'" name="checkbox[]" value="'+data.catalogs[i].id+'"/>'+data.catalogs[i].title+
                                    '<span class="label label-primary">'+data.catalogs[i].count+'</span>';
                    }
                    checkboxes+='</div>';
                    $("div[@data-shop-id='"+shop_id+"']>div.checkboxes>div.list_cat").remove();
                    $("div[@data-shop-id='"+shop_id+"']>div.checkboxes>").append(checkboxes);
                    $("div[@data-shop-id='"+shop_id+"']>span>div.info").addClass('alert alert-success');
                    $("div[@data-shop-id='"+shop_id+"']>span>div.info").html("<span>Время парсинга: '+data.time+'</span>");
                    $("div[@data-shop-id='"+shop_id+"']").parent(".panel").children(".load").addClass("none");
                },
                error: function (data) {
                    alert("Ошибка парсинга магазина"+shop_id+" Error:"+data.value)
                }
            })
        }
    });
</script>
<h2><%= link_to 'Добавить сайт', new_shop_path %></h2>
<% @shop.each do |shop| %>
    <div class="panel panel-primary">
      <div class="panel-heading" style="height: 55px;">
        <label class="title_shop"><%= link_to shop.title, shop %></label>
        <%= link_to image_tag('edit.png', :width => 30, :height => 30, :title => "Редактировать"), edit_shop_path(shop) %>
        <%= link_to image_tag('XLS.png', :width => 30, :height => 30, :title => "Скачать Excel файл"), save_xls_save_path(shop), :class => "img_download" %>
        <%= button_to "Скачать Excel файл", save_xls_save_path(shop) %>
        <div class="load none"></div>
      </div>
      <div class="panel-body">
        <div data-shop-id="<%= shop.id %>">
          <a class="catalog" href="#" title="Раскрыть список каталога"><span><%= image_tag('add.png', :width => 10, :height => 10) %></span>Каталог</a>
          <span class="catalog_button">
            <%= link_to image_tag('refresh.png', :width => 20, :height => 20, :title => 'Обновить каталог'), get_catalogs_parsing_path(shop), :remote => true %>
            <button class="btn  btn-default" data-shop-id="<%= shop.id %>">Парсинг</button>

            <div class="info"></div>
           </span>
<%= button_to "test",get_goods_parsing_path(shop) %>
          <div class="checkboxes">
            <% shop.catalog_shops.map do |cat| %>
                <div class="list_cat none">
                  <input type="checkbox" data-shop-id="<%= shop.id %>" name="checkbox[]" value="<%= cat.id %>" checked="checked"/><%= cat.title %>
                  <span class="label label-primary"><%= cat.products.size %></span>
                  <span>Время скачки: <%= cat.time_download.strftime "%T" unless cat.time_download.nil?%></span>
                  <span>Дата: <%= cat.date_last_download %></span>
                </div>
            <% end %>
            <div class="clearfix"></div>
          </div>

        </div>
      </div>
      <div class="panel-footer">
        <span class="label"><a href='<%= shop.url %>'><%= shop.host %></a></span>
        <span>XPATH:<%= shop.xpath %></span><span style="float: right">Последний парсинг:<i><%= shop.products.order("updated_at DESC").first.updated_at if shop.products.size>0 %></i></span>
      </div>
    </div>

<% end %>

app/views/shops/new.html.erb
<h1>Добавление сайта</h1>

<%= render 'form' %>

<%= link_to 'К списку сайтов', shops_path %>

app/views/shops/show.html.erb
<style>
    .tableL {
        margin: 0 5px;
        float: left;
    }

    .cellsBlock {

        display: table;
        text-align: center;
    }

    .cellSmall, .cellMiddle, .cellMax{
        display: table-cell !important;
        display: inline; /* для IE */
        border: 1px solid black;
    }
    .cellMiddle {
        width: 100px;
    }
    .cellMax {
        width: 200px;
    }
    .cellSmall {
        width: 60px;
    }
</style>
<p>
  <strong>Название:</strong>
  <%= @shop.title %>
</p>

<p>
  <strong>URL:</strong>
  <%= @shop.url %>
</p>
<p>
  <strong>Xpath:</strong>
  <%= @shop.xpath %>
</p>
<p>
  <strong>Host:</strong>
  <%= @shop.host %>
</p>
<div class="tableL">
  <div class="cellsBlock">
    <div class="cellMax">Каталог</div>
    <div class="cellMax">Название</div>
    <div class="cellSmall">Артикул</div>
    <div class="cellSmall">Цена</div>
    <div class="cellSmall">Цвет</div>
    <div class="cellMiddle">Размер</div>
    <div class="cellMax">Описание</div>
    <div class="cellSmall">URL</div>
    <div class="cellSmall">Фото</div>
  </div>
<% @shop.products.each do |pr| %>
      <div class="cellsBlock">
        <div class="cellMax"><%= pr.category_path %></div>
        <div class="cellMax"><%= pr.title %></div>
        <div class="cellSmall"><%= pr.article %></div>
        <% unless Price.where(product_id: pr.id).nil? %>
            <% Price.where(product_id: pr.id).map{|x| %>
                <div class="cellSmall"><%= x.cost %></div>
        <% } end %>
        <div class="cellSmall"><%= pr.color %></div>
        <div class="cellMiddle"><%= pr.size %></div>
        <div class="cellMax"><%= pr.description %></div>
        <div class="cellSmall"><a href="<%= pr.url %>">URL</a></div>
        <% if !Photo.where(product_id: pr.id).nil? %>
            <% Photo.where(product_id: pr.id).each_with_index{|x,i| %>
                <div class="cellSmall"><a href="<%= x.url%>">ФОТО <%= i+1%></a></div>
        <% } end %>
      </div>
<% end %>
  </div>
<%= link_to 'Назад к списку сайтов', shops_path %>
| <%= link_to 'Редактировать', edit_shop_path(@shop) %>