config/routes.rb
KupiNam::Application.routes.draw do

  get "catalog_shops/index"
  get "parsings/index"

  root 'shops#index'
  resources :shops
  resources :parsings
  resources :catalog_shops

     resources :parsings do
       member do
         post 'get_catalogs'
         post 'get_goods'
       end
     end
    resources :save do
      member do
        post 'save_xls'
        post 'save_xlsx'
      end
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KupiNam</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield(:header) if @content_for_header %>
</head>
<!-- Static navbar -->
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to 'KupiNam', shops_path,:class => "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Главная</a></li>
        <li><a href="#about">Вход</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>


<div class="container">
  <%= yield %>
</div> <!-- /container -->

</body>
</html>